name: bennett

services: 
  mysql:
    container_name: mysql
    image: mysql:8.4.0
    restart: always
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bennett_development
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - '3306:3306'
    volumes:
      - /Users/zhangmengmeng/Documents/mysql-data/bennett_mysql:/var/lib/mysql
